
export type Addon = {
  id: string;
  name: string;
  price: number;
  description: string;
};

export type Service = {
  id: string;
  name: string;
  description: string;
  longDescription: string;
  price: number;
  duration: number; // in minutes
  image: string;
  dataAiHint: string;
  category: string;
  professionals: string[]; // ids of professionals
  addons: Addon[];
};

export type Professional = {
  id: string;
  name: string;
  specialty: string;
  image: string;
  dataAiHint: string;
};

export const services: Service[] = [
  // Nail Services
  {
    id: 'nail-classic-mani',
    name: 'Classic Mani',
    description: 'A timeless manicure for a clean and elegant look.',
    longDescription: 'Experience the art of nail care with our Classic Manicure. This service includes meticulous nail shaping, gentle cuticle care, a soothing hand massage to improve circulation, and finishes with a flawless polish application in the color of your choice. It\'s the perfect ritual for maintaining beautiful, healthy hands and a polished, professional appearance.',
    price: 120,
    duration: 45,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'classic manicure',
    category: 'Nails',
    professionals: ['prof2', 'prof5'],
    addons: [],
  },
  {
    id: 'nail-classic-pedi',
    name: 'Classic Pedi',
    description: 'A relaxing pedicure for perfectly polished toes.',
    longDescription: 'Treat your feet to our Classic Pedicure. Begin with a warm, aromatic foot soak, followed by expert nail shaping, cuticle grooming, and gentle callus smoothing. A relaxing foot massage will leave you feeling refreshed, and a perfect polish application will ensure your toes look their best.',
    price: 110,
    duration: 50,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'classic pedicure',
    category: 'Nails',
    professionals: ['prof2', 'prof5'],
    addons: [],
  },
  {
    id: 'nail-combo',
    name: 'Combo Mani + Pedi',
    description: 'The ultimate nail care package for hands and feet.',
    longDescription: 'Indulge in the complete nail care experience with our combined Classic Manicure and Pedicure. This package offers all the benefits of both services at a special value, leaving your hands and feet feeling rejuvenated and looking immaculate. It\'s the perfect way to pamper yourself.',
    price: 210,
    duration: 95,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'manicure pedicure',
    category: 'Nails',
    professionals: ['prof2', 'prof5'],
    addons: [],
  },
  {
    id: 'nail-gel-overlay',
    name: 'Gel Overlay',
    description: 'Strengthening for your natural nails without added length.',
    longDescription: 'A Gel Overlay applies a durable layer of gel directly onto your natural nails, providing strength and protection. This service is perfect for preventing breakage and promoting healthy nail growth, all while maintaining a glossy, long-lasting finish without any extensions.',
    price: 280,
    duration: 75,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'gel nails',
    category: 'Nails',
    professionals: ['prof2', 'prof5'],
    addons: [],
  },
  {
    id: 'nail-polygel-extensions',
    name: 'Polygel Extensions',
    description: 'Lightweight and strong nail extensions for a flawless look.',
    longDescription: 'Polygel Extensions combine the best qualities of acrylic and gel, offering a strong, flexible, and exceptionally lightweight nail enhancement. Achieve your desired length and shape for a flawless, beautiful, and long-lasting result.',
    price: 350,
    duration: 120,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'nail extensions',
    category: 'Nails',
    professionals: ['prof5'],
    addons: [],
  },
  {
    id: 'nail-refill-extensions',
    name: 'Refill Extensions',
    description: 'Maintain your beautiful extensions with a professional refill.',
    longDescription: 'Keep your Polygel or Acrylic extensions looking perfect with our refill service. We will fill in the growth at the base of your nails, rebalance the structure, and ensure they look as good as new.',
    price: 280,
    duration: 90,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'nail refill',
    category: 'Nails',
    professionals: ['prof5'],
    addons: [],
  },
  {
    id: 'nail-removal-gel',
    name: 'Gel/Polygel Removal',
    description: 'Safe and gentle removal of your gel or polygel.',
    longDescription: 'Ensure the health of your natural nails with our professional removal service. We gently and safely remove your gel or polygel enhancements, followed by a light buffing and nail conditioning.',
    price: 150,
    duration: 30,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'nail care',
    category: 'Nails',
    professionals: ['prof2', 'prof5'],
    addons: [],
  },
  {
    id: 'nail-acrylic-natural',
    name: 'Acrylic Extensions - Natural',
    description: 'Classic, durable acrylic extensions for a natural finish.',
    longDescription: 'Achieve beautiful, durable nails with our classic acrylic extensions. This service provides strong and resilient enhancements with a natural-looking finish, customized to your desired length and shape.',
    price: 370,
    duration: 120,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'acrylic nails',
    category: 'Nails',
    professionals: ['prof5'],
    addons: [],
  },
  {
    id: 'nail-acrylic-french',
    name: 'Acrylic Extensions - French',
    description: 'Timeless French tip design with durable acrylics.',
    longDescription: 'The epitome of elegance, our French acrylic extensions provide a timeless, sophisticated look. We create a crisp, white tip on a natural pink base for a beautiful and classic finish.',
    price: 420,
    duration: 135,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'french manicure',
    category: 'Nails',
    professionals: ['prof5'],
    addons: [],
  },
  {
    id: 'nail-acrylic-removal',
    name: 'Acrylic Removal',
    description: 'Safe and professional removal of acrylic extensions.',
    longDescription: 'Protect your natural nails during removal. Our technicians will safely and gently remove your acrylic extensions, followed by nail shaping and conditioning to restore their health.',
    price: 105,
    duration: 45,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'healthy nails',
    category: 'Nails',
    professionals: ['prof5'],
    addons: [],
  },
  {
    id: 'nail-ombre',
    name: 'Ombre (Gel or Acrylic)',
    description: 'A beautiful, blended two-tone nail design.',
    longDescription: 'Achieve a stunning, seamless gradient effect with our Ombre nail service, available in both gel and acrylic. This stylish design blends two complementary colors for a modern and eye-catching look.',
    price: 480,
    duration: 150,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'ombre nails',
    category: 'Nails',
    professionals: ['prof5'],
    addons: [],
  },
  // Eyelash Services
  {
    id: 'lash-classic-full',
    name: 'Classic Full Set (Natural)',
    description: 'Enhance your natural beauty with a full set of classic lashes.',
    longDescription: 'Our Classic Full Set involves applying one individual extension to each of your natural lashes. This method adds length and curl, resulting in a beautifully understated and natural look that enhances your eyes.',
    price: 350,
    duration: 90,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'eyelash extensions',
    category: 'Eyelashes',
    professionals: ['prof2', 'prof4'],
    addons: [],
  },
  {
    id: 'lash-russian-full',
    name: 'Russian Full Set (Volume)',
    description: 'Achieve a dramatic and full look with Russian volume lashes.',
    longDescription: 'For those who desire maximum glamour, the Russian Full Set is the ultimate choice. Our lash artists meticulously create and apply lightweight fans of multiple extensions to each natural lash, resulting in a dense, fluffy, and dramatic look.',
    price: 420,
    duration: 120,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'volume lashes',
    category: 'Eyelashes',
    professionals: ['prof2', 'prof4'],
    addons: [],
  },
  {
    id: 'lash-classic-half',
    name: 'Classic Half Set',
    description: 'A subtle enhancement for the outer corners of your eyes.',
    longDescription: 'Perfect for a subtle, cat-eye effect, our Classic Half Set focuses on applying extensions to the outer corners of your eyes, gradually blending them into your natural lashes for a gentle lift and enhancement.',
    price: 250,
    duration: 60,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'natural lashes',
    category: 'Eyelashes',
    professionals: ['prof2', 'prof4'],
    addons: [],
  },
  {
    id: 'lash-russian-half',
    name: 'Russian Half Set',
    description: 'Add volume to the outer corners for a winged look.',
    longDescription: 'This service provides the glamorous, winged effect of volume lashes by concentrating lightweight fans on the outer half of your lash line. It creates a striking, voluminous finish that beautifully elongates the eyes.',
    price: 350,
    duration: 75,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'winged eyeliner',
    category: 'Eyelashes',
    professionals: ['prof2', 'prof4'],
    addons: [],
  },
  {
    id: 'lash-refill-classic',
    name: 'Classic Lash Refill',
    description: 'Maintain your classic lashes with a timely refill.',
    longDescription: 'Keep your classic lashes looking full and fresh. We recommend a refill every 2-3 weeks to replace any extensions that have naturally shed and to maintain the beautiful, full look of your initial set.',
    price: 200,
    duration: 60,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'lash care',
    category: 'Eyelashes',
    professionals: ['prof2', 'prof4'],
    addons: [],
  },
  {
    id: 'lash-refill-russian',
    name: 'Russian Lash Refill',
    description: 'Keep your voluminous Russian lashes looking their best.',
    longDescription: 'Maintain the drama and fullness of your Russian volume set. This refill service, recommended every 2-3 weeks, involves applying new fans to new lash growth, ensuring your voluminous look remains flawless.',
    price: 250,
    duration: 75,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'glamorous eyes',
    category: 'Eyelashes',
    professionals: ['prof2', 'prof4'],
    addons: [],
  },
  {
    id: 'lash-lift',
    name: 'Lash Lift',
    description: 'Curl and lift your natural lashes for a wide-eyed look.',
    longDescription: 'A lash lift is a fantastic alternative to extensions. This treatment gives your natural lashes a beautiful, upward curl, creating the illusion of longer, fuller lashes. Results last for 6-8 weeks.',
    price: 175,
    duration: 50,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'lash lift',
    category: 'Eyelashes',
    professionals: ['prof2', 'prof4'],
    addons: [],
  },
  {
    id: 'lash-lift-tint',
    name: 'Lash Lift + Tint',
    description: 'Lift and darken your natural lashes for stunning definition.',
    longDescription: 'Combine the benefits of a lash lift with a custom tint. This service curls your lashes from the root and adds a dark tint, providing dramatic definition and making your eyes pop without any makeup. The perfect low-maintenance solution.',
    price: 250,
    duration: 60,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'defined eyes',
    category: 'Eyelashes',
    professionals: ['prof2', 'prof4'],
    addons: [],
  },
  {
    id: 'lash-removal',
    name: 'Eyelash Removal',
    description: 'Safe and professional removal of lash extensions.',
    longDescription: 'Safely and gently remove your lash extensions with our professional service. We use a specially formulated remover that dissolves the adhesive without damaging your natural lashes, leaving them healthy and intact.',
    price: 100,
    duration: 30,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'gentle skincare',
    category: 'Eyelashes',
    professionals: ['prof2', 'prof4'],
    addons: [],
  },
  // Massage Services
  {
    id: 'massage-sports',
    name: 'Sports Massage',
    description: 'Target muscle tension and improve flexibility.',
    longDescription: 'Ideal for athletes or those with active lifestyles, our Sports Massage focuses on preventing and treating injuries. It uses a variety of techniques to stretch muscles, improve flexibility, and enhance athletic performance, helping you stay at the top of your game.',
    price: 300,
    duration: 60,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'sports therapy',
    category: 'Massage',
    professionals: ['prof1', 'prof3', 'prof6'],
    addons: [],
  },
  {
    id: 'massage-relaxation',
    name: 'Relaxation Massage',
    description: 'A gentle massage to soothe and de-stress.',
    longDescription: 'Drift into a state of pure bliss with our Relaxation Massage. This treatment uses smooth, flowing strokes to promote deep relaxation, relieve muscle tension, and improve circulation, leaving you feeling calm, centered, and rejuvenated.',
    price: 300,
    duration: 60,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'serene spa',
    category: 'Massage',
    professionals: ['prof1', 'prof3', 'prof6'],
    addons: [],
  },
  {
    id: 'massage-aromatherapy',
    name: 'Aromatherapy Massage',
    description: 'A soothing massage using essential oils.',
    longDescription: 'Enhance your massage experience with the power of scent. Our Aromatherapy Massage combines the benefits of a relaxation massage with carefully selected essential oils to address your specific needs, whether it\'s to calm, energize, or uplift your senses.',
    price: 300,
    duration: 60,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'essential oils',
    category: 'Massage',
    professionals: ['prof1', 'prof3'],
    addons: [],
  },
  {
    id: 'massage-deep-tissue',
    name: 'Deep Tissue Massage',
    description: 'Release chronic muscle tension with firm pressure.',
    longDescription: 'Our Deep Tissue Massage uses slow, firm strokes and sustained pressure to target the inner layers of your muscles and connective tissues. It is highly effective for relieving chronic aches and pains, such as a stiff neck, upper back pain, and sore shoulders.',
    price: 300,
    duration: 60,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'muscle relief',
    category: 'Massage',
    professionals: ['prof1', 'prof3', 'prof6'],
    addons: [],
  },
  {
    id: 'massage-hot-stone',
    name: 'Hot Stone Massage',
    description: 'Melt away tension with heated basalt stones.',
    longDescription: 'This therapeutic massage uses smooth, heated basalt stones placed on key points of the body. The warmth penetrates deep into the muscles, melting away tension, easing muscle stiffness, and increasing circulation for a deeply restorative experience.',
    price: 330,
    duration: 60,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'hot stones',
    category: 'Massage',
    professionals: ['prof1', 'prof3'],
    addons: [],
  },
  {
    id: 'massage-couples-relaxation',
    name: 'Couples Relaxation Massage',
    description: 'Enjoy a relaxing massage experience side-by-side.',
    longDescription: 'Share a moment of tranquility with our Couples Relaxation Massage. Performed in the same room, this treatment allows you and a partner to unwind and de-stress together, making it a perfect experience for anniversaries, special occasions, or simply a shared escape.',
    price: 500,
    duration: 60,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'couples spa',
    category: 'Massage',
    professionals: ['prof1', 'prof3', 'prof6'],
    addons: [],
  },
   // Facials
  {
    id: 'facial-acne',
    name: 'Acne Treatment Facial',
    description: 'Targets acne and blemishes, reducing inflammation.',
    longDescription: 'Our Acne Treatment Facial is designed to combat acne and blemishes. This purifying treatment deeply cleanses the skin to unclog pores, reduce inflammation, and implement strategies to prevent future breakouts, promoting a clearer, healthier complexion.',
    price: 353,
    duration: 60,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'clear skin',
    category: 'Facials',
    professionals: ['prof2', 'prof4'],
    addons: [],
  },
  {
    id: 'facial-anti-aging',
    name: 'Anti-Aging Facial',
    description: 'Smooths fine lines and promotes a youthful complexion.',
    longDescription: 'Turn back the clock with our Anti-Aging Facial. This treatment uses powerful, active ingredients and advanced techniques to combat the signs of aging. It helps to smooth fine lines and wrinkles, boost collagen production, and promote a firmer, more radiant, and youthful complexion.',
    price: 419,
    duration: 75,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'youthful skin',
    category: 'Facials',
    professionals: ['prof2', 'prof4'],
    addons: [],
  },
  {
    id: 'facial-deep-cleansing',
    name: 'Deep Cleansing Facial',
    description: 'Unclogs pores and removes impurities for clear skin.',
    longDescription: 'This essential facial is designed to deeply cleanse your skin, effectively unclogging pores and removing impurities. Through gentle exfoliation and extraction, it leaves your skin feeling exceptionally clean, refreshed, and clear.',
    price: 353,
    duration: 60,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'facial cleansing',
    category: 'Facials',
    professionals: ['prof2', 'prof4'],
    addons: [],
  },
  {
    id: 'facial-deep-hydrating',
    name: 'Deep Hydrating Facial',
    description: 'Replenishes moisture and rejuvenates dry, dehydrated skin.',
    longDescription: 'Quench your skin\'s thirst with our Deep Hydrating Facial. Ideal for dry or dehydrated skin, this treatment uses intensely moisturizing ingredients to replenish hydration levels, leaving your skin soft, supple, plump, and glowing with health.',
    price: 364,
    duration: 60,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'hydrated skin',
    category: 'Facials',
    professionals: ['prof2', 'prof4'],
    addons: [],
  },
   // Body Treatments
  {
    id: 'scrub-coffee',
    name: 'Arabica Coffee Scrub',
    description: 'Exfoliates and helps reduce the appearance of cellulite.',
    longDescription: 'Invigorate your skin with our Arabica Coffee Scrub. This stimulating treatment exfoliates away dull, dead skin cells, boosts circulation, and helps to reduce the appearance of cellulite, leaving your skin feeling smooth, firm, and energized.',
    price: 650,
    duration: 45,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'coffee scrub',
    category: 'Body Treatments',
    professionals: ['prof1', 'prof2'],
    addons: [],
  },
  {
    id: 'scrub-himalayan',
    name: 'Himalayan Salt Scrub',
    description: 'Detoxifies and revitalizes the skin.',
    longDescription: 'This detoxifying body scrub uses pure, mineral-rich Himalayan salt to exfoliate the skin, draw out impurities, and replenish essential minerals. It leaves your skin feeling incredibly soft, smooth, and revitalized.',
    price: 650,
    duration: 45,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salt scrub',
    category: 'Body Treatments',
    professionals: ['prof1', 'prof2'],
    addons: [],
  },
  {
    id: 'scrub-gold',
    name: '24k Gold Scrub',
    description: 'Creating a radiant, youthful complexion.',
    longDescription: 'Indulge in the ultimate luxury with our 24k Gold Scrub. This opulent treatment gently exfoliates while imparting the anti-aging and illuminating benefits of gold, leaving your skin with a radiant, youthful glow.',
    price: 650,
    duration: 45,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'gold treatment',
    category: 'Body Treatments',
    professionals: ['prof1', 'prof2'],
    addons: [],
  },
  {
    id: 'facial-addons',
    name: 'Facial Add-Ons & Masks',
    description: 'Customize your facial with our potent add-ons.',
    longDescription: 'Elevate your facial experience with our range of high-performance add-ons and masks. From the rejuvenating power of an LED Mask to the luxurious touch of a 24K Gold Mask, you can customize your treatment to target your specific skin concerns and achieve spectacular results.',
    price: 350, // Starting from price
    duration: 15,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'facial mask',
    category: 'Facials',
    professionals: ['prof2', 'prof4'],
    addons: [
      { id: 'addon-led', name: 'LED Mask', price: 850, description: 'Rejuvenate your complexion with targeted LED light therapy.' },
      { id: 'addon-high-freq', name: 'High Frequency', price: 850, description: 'Enhance skin condition for both scalp and face.' },
      { id: 'addon-gold-mask', name: '24K Gold Mask', price: 750, description: 'A luxurious, revitalizing gold-infused facial mask.' },
      { id: 'addon-diamond-mask', name: 'Diamond Mask', price: 350, description: 'Polishes the skin, boosts radiance, and smooths fine lines.' },
      { id: 'addon-vit-c', name: 'Vitamin C Boost', price: 350, description: 'Brightens and evens out skin tone.' },
      { id: 'addon-hyaluronic', name: 'Hyaluronic Acid Ampoule', price: 350, description: 'Deeply moisturizes and plumps fine lines.' },
    ],
  },
  {
    id: 'massage-addons',
    name: 'Add-On Massage',
    description: 'Extend your relaxation with a focused massage add-on.',
    longDescription: 'Enhance any massage or body treatment with one of our targeted add-ons. Whether you need extra attention on your feet with reflexology or want to relieve tension with a head massage, these additions allow you to customize your experience for maximum benefit.',
    price: 50, // Starting from price
    duration: 15,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'focused massage',
    category: 'Massage',
    professionals: ['prof1', 'prof3', 'prof6'],
    addons: [
      { id: 'addon-foot', name: 'Foot Reflexology (15 min)', price: 50, description: 'Target pressure points in the feet.' },
      { id: 'addon-head', name: 'Head Massage (15 min)', price: 50, description: 'Relieve tension in your head and scalp.' },
      { id: 'addon-neck-shoulder', name: 'Neck & Shoulder (15 min)', price: 50, description: 'Focus on releasing upper body tension.' },
    ],
  },
];


export const professionals: Professional[] = [
  {
    id: 'prof1',
    name: 'Aisha Al Marzooqi',
    specialty: 'Massage Therapist',
    image: 'https://placehold.co/100x100.png',
    dataAiHint: 'woman portrait',
  },
  {
    id: 'prof2',
    name: 'Fatima Al Jaber',
    specialty: 'Esthetician & Lash Artist',
    image: 'https://placehold.co/100x100.png',
    dataAiHint: 'elegant woman',
  },
  {
    id: 'prof3',
    name: 'Saeed Al Maktoum',
    specialty: 'Holistic Massage Expert',
    image: 'https://placehold.co/100x100.png',
    dataAiHint: 'man portrait',
  },
  {
    id: 'prof4',
    name: 'Layla Al Shamsi',
    specialty: 'Skincare Specialist',
    image: 'https://placehold.co/100x100.png',
    dataAiHint: 'professional woman',
  },
  {
    id: 'prof5',
    name: 'Noora Al Hashimi',
    specialty: 'Master Nail Technician',
    image: 'https://placehold.co/100x100.png',
    dataAiHint: 'woman smiling',
  },
  {
    id: 'prof6',
    name: 'Khalid Al Balushi',
    specialty: 'Sports & Deep Tissue Therapist',
    image: 'https://placehold.co/100x100.png',
    dataAiHint: 'professional man',
  },
];

export const timeSlots = ["09:00 AM", "11:00 AM", "01:00 PM", "03:00 PM", "05:00 PM", "07:00 PM"];
